### PR TITLE
fix(deadline): lock down DocDC engine to version 3.6.0

### LINKED ISSUE #229: DocDB version is not locked to v3.6 for Deadline
Officially, Deadline only supports version 3.6 of the MongoDB API. Amazon DocumentDB has just GA'd their 4.0 engine ( https://aws.amazon.com/blogs/database/introducing-amazon-documentdb-with-mongodb-compatibility-4-0/ ).

According to the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-engineversion), the DocumentDB cluster defaults to the latest engine version when being created -- this is now 4.0.0. In a quick test, it looks like the default is still to create a 3.6.0 engine, but I think we can safely assume that will change.

### Other

Fix will be to simply specify the engine version for Document DB as 3.6.0.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ddneilson**
Fixes: https://github.com/aws/aws-rfdk/issues/229

## Testing

Did a quick deploy of the Deadline Repository & RCS. Verified it deployed successfully, and the DocDB engine version was correct. Also changed the engine version to 4.0.0 and did the same to verify that it changed there too.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-rfdk/lib/deadline/lib/repository.ts [hunk 1]
```diff
@@ -490,6 +490,7 @@ export class Repository extends Construct implements IRepository {
       const instances = props.documentDbInstanceCount ?? Repository.DEFAULT_NUM_DOCDB_INSTANCES;
       const dbCluster = new DatabaseCluster(this, 'DocumentDatabase', {
         masterUser: {username: 'DocDBUser'},
+        engineVersion: '3.6.0',
```
Comment (jusiskin) [inline packages/aws-rfdk/lib/deadline/lib/repository.ts:494]: Two things:

1.  This is good for the case where `props.database` is not supplied, but is it possible to add validation that the engine is correct for the code path where a caller specifies their own cluster and fail-fast?
1.  Can we add a test for this new behavior?

**Review by jusiskin — CHANGES_REQUESTED** [review]
Can we add some guidance to the relevant TSDoc entries? I'm thinking good places might be:
*   the `Repository` construct
*   the `DatabaseConnection.forDocDB` method.

I was also hopeful we could perform a pre-flight run-time validation, but unfortunately it looks like the engine version is not available as a [`DatabaseCluster` attribute](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-docdb.DatabaseCluster.html#properties).

File: packages/aws-rfdk/lib/deadline/lib/repository.ts (hunk 1 above)
Comment (ddneilson) [reply packages/aws-rfdk/lib/deadline/lib/repository.ts:494]: It's a good idea. I'll see what I can cobble together.

File: packages/aws-rfdk/lib/deadline/lib/database-connection.ts [hunk 2]
```diff
@@ -256,6 +262,25 @@ class DocDBDatabaseConnection extends DatabaseConnection {
...
+  protected isCompatibleDocDBVersion(): boolean {
+    // The defaultChild of a DocDB DatabaseCluster is a CfnDBCluster, but we only have this
+    // child if the customer didn't import from attributes. We can check the DB version by
+    // checking the value of the engineVersion property of that object.
+    if (this.props.database.node.defaultChild) {
+      const cluster = this.props.database.node.defaultChild! as CfnDBCluster;
+      if (cluster.engineVersion === '3.6.0') {
+        return true;
+      }
+      return false;
```
Comment (jusiskin) [inline packages/aws-rfdk/lib/deadline/lib/database-connection.ts]: Looks good. I'm just thinking in the event that DocDB issues a patch version for 3.6. Just in case, should we relax the final version component here? So:

```ts
return cluster.engineVersion.startsWith('3.6.');
```

It looks like RDS has patch engine versions for other DB types:

```sh
$ aws docdb describe-db-engine-versions --engine mariadb --engine-version 10.0.17
{
    "DBEngineVersions": [
        {
            "Engine": "mariadb",
            "EngineVersion": "10.0.17",
...
```

File: packages/aws-rfdk/lib/deadline/lib/repository.ts [hunk 3]
```diff
@@ -288,6 +288,7 @@ export interface RepositoryProps {
 
   /**
    * Specify the database where the deadline schema needs to be initialized.
+   * Note that Deadline supports only databases that are compatible with MongoDB 3.6.
```
Comment (jusiskin) [inline packages/aws-rfdk/lib/deadline/lib/repository.ts:291]: This looks great. I had also suggested adding something to the TSDoc string of `DatabaseConnection.forDocDB` too.  Perhaps even `DocDBConnectionOptions.database`. What do you think?

File: packages/aws-rfdk/lib/deadline/lib/database-connection.ts [hunk 4]
```diff
@@ -163,6 +165,10 @@ class DocDBDatabaseConnection extends DatabaseConnection {
   constructor(private readonly props: DocDBConnectionOptions) {
     super();
 
+    if (!this.isCompatibleDocDBVersion()) {
+      Annotations.of(props.database).addError('engineVersion must be 3.6.0 to be compatible with Deadline');
```
Comment (jusiskin) [inline packages/aws-rfdk/lib/deadline/lib/database-connection.ts:173]: same comment as below. Should we relax this message to `3.6.x`

**Review by jusiskin — CHANGES_REQUESTED** [review]

File: packages/aws-rfdk/lib/deadline/lib/repository.ts (hunk 3 above)
Comment (ddneilson) [reply packages/aws-rfdk/lib/deadline/lib/repository.ts:291]: Ah, right. Sure. I can add something there...

File: packages/aws-rfdk/lib/deadline/lib/database-connection.ts (hunk 2 above)
Comment (ddneilson) [reply packages/aws-rfdk/lib/deadline/lib/database-connection.ts]: No harm in doing that, though the DocDB service team will never have any 3.6 value other than 3.6.0 and similarly, no 4.0 other than 4.0.0. They specifically don't do patch versions.

**Review by jusiskin — DISMISSED** [review]
Looks good. Approved!

File: packages/aws-rfdk/lib/deadline/lib/database-connection.ts (hunk 4 above)
Comment (horsmand) [reply packages/aws-rfdk/lib/deadline/lib/database-connection.ts:173]: This still says 3.6.0 but our other messaging and the version check all use 3.6

File: packages/aws-rfdk/lib/deadline/lib/repository.ts (hunk 3 above)
Comment (horsmand) [reply packages/aws-rfdk/lib/deadline/lib/repository.ts:291]: The comment for `DocDBConnectionOptions.database` wasn't updated, do we need that too?

File: packages/aws-rfdk/lib/deadline/lib/database-connection.ts (hunk 4 above)
Comment (ddneilson) [reply packages/aws-rfdk/lib/deadline/lib/database-connection.ts:173]: Ah, I discussed this with Josh offline. DocumentDB doesn't do patch-level versions. It will always be 3.6.0

File: packages/aws-rfdk/lib/deadline/lib/repository.ts (hunk 3 above)
Comment (ddneilson) [reply packages/aws-rfdk/lib/deadline/lib/repository.ts:291]: Added those too in latest rev.

**Review by horsmand — APPROVED** [review]

**Review by jusiskin — APPROVED** [review]
Great job! Thanks @ddneilson
