### PR TITLE
fix(deadline): fix import and HTTPS redirect errors in stage-deadline

### LINKED ISSUE #177: stage-deadline errors for RFDK 0.18.0
# Description

There are two issues with the `stage-deadline` script in the RFDK 0.18.0 release.

## 1. Failed import of `aws-sdk`

Running the `stage-deadline` script in isolation is useful for quickly importing Deadline assets for use by the app, and also is used in our integration tests, and is also currently the expected way to stage Deadline for a Python app. This does not work for RFDK 0.18.0 and it outputs the error:

    Cannot find module 'aws-sdk'

### Reproduction Steps

1. Clone the RFDK
1. `cd` to the `examples/deadline/All-In-AWS-Infrastructure-Basic/python` directory
1. Install dependencies with `python setup.py install`
1. Execute `npx --package=aws-rfdk@0.18.0 stage-deadline 10.1.9.2`

### Actual Result

```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'aws-sdk'
Require stack:
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/dynamodb/composite-table.js
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/dynamodb/index.js
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/custom-resource/dynamo-backed-resource.js
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/custom-resource/index.js
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/version-provider/handler.js
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/version-provider/index.js
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/bin/stage-deadline.js
- /local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/bin/stage-deadline
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/dynamodb/composite-table.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/dynamodb/composite-table.js',
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/dynamodb/index.js',
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/custom-resource/dynamo-backed-resource.js',
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/lib/custom-resource/index.js',
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/version-provider/handler.js',
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/lib/core/lambdas/nodejs/version-provider/index.js',
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/bin/stage-deadline.js',
    '/local/home/painec/.npm/_npx/18416/lib/node_modules/aws-rfdk/bin/stage-deadline'
  ]
}
```
### Expected Result

The script executes and downloads Deadline assets to the `stage` folder

### Workaround
Typescript apps can locally run `npx stage-deadline 10.1.9.2`, but Python apps cannot, so for Python the user has to stage Deadline elsewhere and copy the staging folder over

### Environment

  - **RFDK Version:** 0.18.0
  - **Deadline Version:** 10.1.9.2
  - **Node.js Version:** 12.18.3
  - **OS               :** AL2

### Other

I tried installing the missing module with `npm install -g aws-sdk` but it didn't help.

## 2. HTTP 301 Redirect from HTTP -> HTTPS causes abort

When the `aws-sdk` is available in the node search path, a different error message is displayed:

    Expected status code 200, but got 301

### Reproduction Steps

1.  Clone the RFDK
1.  Build the project (`./build.sh`)
1.  `cd examples/deadline/All-In-AWS-Infrastructure-Basic/ts`
1.  Run `npx stage-deadline`

### Actual Result

```
Expected status code 200, but got 301
```

### Expected Result

The script executes and downloads Deadline assets to the `stage` folder

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jusiskin**
Fixes #177

## Problem

There are two issues with the `stage-deadline` script in RFDK 0.18.0 (see #177):

### 1.  Failed import of `aws-sdk`

The `stage-deadline.ts` file imported some code from the shared lambda directory:

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/bin/stage-deadline.ts#L15

This then imports from `handler.ts`:

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/index.ts#L6

Which imports from `custom-resource.ts`:

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/handler.ts#L9

Which imports from `dynamo-backed-resource.ts`:

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lambdas/nodejs/lib/custom-resource/index.ts#L6

Which imports the `aws-sdk`:

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lambdas/nodejs/lib/custom-resource/dynamo-backed-resource.ts#L9

This causes an import error when running the command through `npx` since we do not specify `aws-sdk` in the [list of dependencies for the `aws-rfdk` package](https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/package.json#L78-L131) that contains `stage-deadline`.

### 2.  HTTP 301 Redirect from HTTP -> HTTPS causes abort

The `VersionProvider` class uses [Node.JS's built-in `http` module](https://nodejs.org/api/http.html) to fetch the download index.

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/version-provider.ts#L157

But, the download index is an HTTPS URL: 

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/version-provider.ts#L147

The `http` module appears to accept the `https://` URL, but makes a plain-HTTP request. The response comes back as an HTTP 301 redirect. The `VersionProvider` handles this as an error:

https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/version-provider.ts#L167-L177

## Solution

Create a 0.18.1 patch release of RFDK that resolves the two bugs mentioned above. Each of the fix is addressed in their own commit. Summary of the changes:

### 1.  Failed import of `aws-sdk`

Import the symbols directly from `packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/version-provider' to avoid the import of `aws-sdk`.

### 2. HTTP 301 Redirect from HTTP -> HTTPS causes abort

Replaced the usage of `http` module with `https`.

### Patch release

Created a bump commit that increments the patch version. Also note that this pull request targets the `releases/0.18.1` branch. Once this is merged, a release pipeline will be ran against this branch.

Follow-up PR(s) will be created to merge the fixing commits back to the `mainline` branch.

### Reproduce issue using a dev build

1.  Created a new CDK application in a separate directory:

    ```bash
     npx cdk@1.66.0 init --language typescript
    ```
1.  Link the dev build using the `link-all.sh` script

    ```bash
    ${PATH_TO_RFDK_CHECKOUT}/link-all.sh
    ```
1.  Rename the `aws-sdk` directory in `${PATH_TO_RFDK_CHECKOUT}/node_modules` to `aws-sdk2`
1.  Attempt to stage Deadline:

    ```bash
    npx stage-deadline
    ```
1.  Confirmed I get the reproduced error message:

        Cannot find module 'aws-sdk'

### After fixing confirm the errors are gone and Deadline is staged

1.  Same process as above after applying the fix to my changes to my RFDK development build
1.  Confirmed no errors and Deadline is staged:

    ```bash
    $ tree stage
    stage
    ├── bin
    │   └── DeadlineClient-10.1.10.6-linux-x64-installer.run
    ├── deadline_docker
    ├── dlconfig
    │   ├── client-rq-connection
    │   ├── dlconfig
    │   ├── fetch_file
    │   ├── fetch_secret
    │   └── json-query
    ├── dldocker
    │   ├── commands.py
    │   ├── docker.py
    │   ├── formatters.py
    │   ├── __init__.py
    │   ├── __main__.py
    │   ├── manifest.py
    │   └── recipe.py
    ├── Dockerfile
    ├── LICENSE
    ├── license-forwarder
    │   ├── README.md
    │   └── root
    │       ├── app
    │       │   └── configure-license-forwarder.sh
    │       └── dlconfig
    │           ├── ubl-certificates
    │           ├── ubl-limits
    │           └── ubl_limits.py
    ├── manifest.json
    ├── NOTICE
    ├── rcs
    │   ├── README.md
    │   └── root
    │       ├── app
    │       │   └── configure-rcs.sh
    │       └── dlconfig
    │           ├── database-credentials
    │           ├── direct-repo-connection
    │           └── rcs-tls
    └── README.md

    11 directories, 29 files
    ```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-rfdk/bin/stage-deadline.ts [hunk 1]
```diff
@@ -12,7 +12,12 @@ import * as fs from 'fs';
 import * as path from 'path';
 import * as url from 'url';
 import { types } from 'util';
-import {IUris, Platform, Product, VersionProvider } from '../lib/core/lambdas/nodejs/version-provider';
+import {
+  IUris,
+  Platform,
+  Product,
+  VersionProvider,
+} from '../lib/core/lambdas/nodejs/version-provider/version-provider';
```
Comment (ddneilson) [inline packages/aws-rfdk/bin/stage-deadline.ts]: This fix, to me, says that `version-provider.ts` should actually have been in a `lib/core/lambdas/nodejs/lib/version-provider/` rather than in the same module as the `VersionQuery` custom resource handler.

**Review by ddneilson — CHANGES_REQUESTED** [review]

**Review by horsmand — APPROVED** [review]

File: packages/aws-rfdk/bin/stage-deadline.ts (hunk 1 above)
Comment (horsmand) [reply packages/aws-rfdk/bin/stage-deadline.ts]: I just approved this PR, but this suggestion makes sense to me as well.

Comment (jusiskin) [reply packages/aws-rfdk/bin/stage-deadline.ts]: Do you think we should be doing this now given `stage-deadline` doesn't work for RFDK 0.18.0? Making that kind of change would probably warrant more testing and potentially cause conflicts in #175. How would you feel about postponing that change to be in #175? Or possibly as a part of #146?

Comment (ddneilson) [reply packages/aws-rfdk/bin/stage-deadline.ts]: #175 is in-progress and can be rebased easily enough. The only live code that uses `version-provider.ts` is this stage-deadline script. IMO, I'd rather just do the correct fix and force an update of #175 rather than go with a quick-fix now and kick the can down the road.

Comment (jusiskin) [reply packages/aws-rfdk/bin/stage-deadline.ts]: I've made the change.

**Comment by jusiskin** [comment]
Heads up: when merging, please don't squash the commits, since they are already written using conventional commits and one includes the bump commit that needs to be separate for our release automation.

**Review by ddneilson — APPROVED** [review]
