### PR TITLE
fix(deadline): Windows WorkerInstanceFleets with Deadline 10.1.14 installed fail deployment

### LINKED ISSUE #312: configureWorker.sh attempts to start Launcher in GUI mode
It seems we have an issue in configureWorker.sh where [we attempt to start the Launcher in GUI mode](https://github.com/aws/aws-rfdk/blob/6e518d4c9e85f53edfba4a9f8f97d7712d882fe1/packages/aws-rfdk/lib/deadline/scripts/bash/configureWorker.sh#L136) if it was not installed as a service which throws the following error in the cloud-init script:

```
QXcbConnection: Could not connect to display 
QXcbConnection: Could not connect to display 
"/tmp/assets/1234567bc1d4fd78061765b059dcc8e32568828e5cf479b08115489651491c8f.sh: line 137:  3296 Aborted                 ""$DEADLINE_LAUNCHER"""
```

I believe the workaround is to include the `-nogui` flag to the parameters

### Reproduction Steps

1. Build a Worker AMI where the Launcher has not been installed as a service
2. Use the [example from What is RFDK?](https://docs.aws.amazon.com/rfdk/latest/guide/what-is-rfdk.html) and plug this AMI id into the configuration

### Error Log

```
1612823870830,DEBUG: The Worker is also capable of decompressing responses using Brotli
1612823870830,Successfully set ip-10-248-3-190 to listen on port 56032
1612823870830,+ port_offset=1
1612823870830,+ service --status-all
1612823870830,+ grep -q 'Deadline 10 Launcher'
1612823870830,+ DEADLINE_LAUNCHER=/opt/Thinkbox/Deadline10/bin/deadlinelauncher
1612823871080,+ /opt/Thinkbox/Deadline10/bin/deadlinelauncher -shutdownall
1612823871080,No Launcher to shutdown
1612823871080,+ sudo killall -w deadlineworker
1612823871080,deadlineworker: no process found
1612823871080,+ true
1612823871330,+ /opt/Thinkbox/Deadline10/bin/deadlinelauncher
1612823871330,daemon was not added to the CommandLineParser.
1612823871330,daemon was not added to the CommandLineParser.
1612823871830,DEBUG: The Worker is also capable of decompressing responses using Brotli
1612823871830,Auto Configuration: Picking configuration based on: ip-10-248-3-190.example.com / 10.248.3.190
1612823871830,"Auto Configuration: No auto configuration could be detected, using local configuration"
1612823871830,Launcher Thread - Launcher thread initializing...
1612823871830,Launcher Thread - opening remote TCP listening port 17000
1612823871830,Launcher Thread - creating local listening TCP socket on an available port...
1612823871830,Launcher Thread - local TCP port bound to: [::1]:34433
1612823871830,Launcher Thread -  updating local listening port in launcher file: 34433
1612823871830,Launcher Thread - Launcher thread listening on port 17000
1612823871830,upgraded was not added to the CommandLineParser.
1612823871830,upgradefailed was not added to the CommandLineParser.
1612823871830,service was not added to the CommandLineParser.
1612823872080,daemon was not added to the CommandLineParser.
1612823872830,Launching Worker: 
1612823872830,Launcher Thread - Remote Administration is now disabled
1612823877414,Launcher Thread - Automatic Updates is now disabled
1612823881834,QXcbConnection: Could not connect to display 
1612823881834,QXcbConnection: Could not connect to display 
1612823882334,"/tmp/assets/1234563bc1d4fd78061765b059dcc8e32568828e5cf479b08115489651491c8f.sh: line 137:  3296 Aborted                 ""$DEADLINE_LAUNCHER"""
1612823882334,Feb 08 22:38:02 cloud-init[2513]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [134]
1612823882334,Feb 08 22:38:02 cloud-init[2513]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
1612823882334,Feb 08 22:38:02 cloud-init[2513]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
1612823886414,"Cloud-init v. 19.3-5.amzn2 finished at Mon, 08 Feb 2021 22:38:02 +0000. Datasource DataSourceEc2.  Up 109.73 seconds"
```

### Environment

  - **CDK CLI Version      : Unknown
  - **CDK Framework Version: Unknown
  - **RFDK Version: Main
  - **Deadline Version: 10.1.13
  - **Node.js Version: Unknown
  - **OS               : Unknown
  - **Language (Version): Python (Unknown)

### Other

--- 

This is :bug: Bug Report

### LINKED ISSUE #353: WorkerInstanceFleet fails deployment for Windows instances
The `WorkerInstanceFleet` construct fails to deploy its ASG instances when configured to deploy Windows AMIs with Deadline 10.1.14.x. 

### Reproduction Steps

all Windows Worker fleet integration tests currently fail using the defaults (latest Deadline version of 10.1.14.5).

### Error Log

The `cdk deploy` output shows:

```
4:50:57 AM | CREATE_FAILED        | AWS::AutoScaling::AutoScalingGroup          | WorkerStructWF2/Worker3/Default/ASG
Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

When looking at the userdata CloudWatch logs, the following is seen:

```
2021/03/20 06:28:28Z: <powershell> tag was provided.. running powershell content
2021/03/20 06:30:31Z: Userdata:  is currently executing. To end it kill the process with id: 3880
2021/03/20 06:32:32Z: Userdata:  is currently executing. To end it kill the process with id: 3880
2021/03/20 06:34:34Z: Userdata:  is currently executing. To end it kill the process with id: 3880
...
```

### Environment

  - **CDK CLI Version      :** 1.91.0
  - **CDK Framework Version:** 1.91.0
  - **RFDK Version:** 0.27.0
  - **Deadline Version:** 10.1.14.5
  - **Node.js Version:** Any
  - **OS               :** Amazon Linux 2
  - **Language (Version):** All

### Other

This was not occurring in the integration tests for the 0.27.0 release. At that time, the latest Deadline version available to RFDK was 10.1.13.2.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jusiskin**
## Problem

Primarily #353, but also fixes #312.

>   The `WorkerInstanceFleet` construct fails to deploy its ASG instances when configured to deploy Windows AMIs with Deadline 10.1.14.x.

The real issue is a Deadline bug where stopping or restarting the launcher Windows service while it's still starting up can get stuck. The windows service gets stuck in a `stopping` state and the only way to unlock the service is to kill the process.

RFDK restarts the launcher twice when configuring workers in relatively quick succession. There is a race condition between restarting the service the first time and the second restart. Once Deadline 10.1.14 was available to RFDK, the race became more probable to fail. The result is that the user data generated by RFDK to configure Windows workers never completes to send the CloudFormation signal and deployments fail.

## Solution

Modified the `RenderQueueConnection` sub-classes to accept an optional `restartLauncher` property. The default was made true to preserve backwards-compatible behavior when this API is called directly. When called by `WorkerInstanceConfiguration`, this flag is set to `false` because it needs to restart the Deadline Launcher again later after configuring the remote command listener ports. By reducing the number of launcher service restarts to one, we avoid the race condition.

## Testing

Ran the integration tests using this branch and they now all pass.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-rfdk/lib/deadline/lib/rq-connection.ts [hunk 1]
```diff
@@ -114,23 +124,31 @@ export abstract class RenderQueueConnection {
...
-        '  & "$DEADLINE_PATH/deadlinelauncher.exe" 2>&1',
-        '}',
       );
+      if (args.restartLauncher ?? true) {
+        host.userData.addCommands(
+          'If (Get-Service "deadline10launcherservice" -ErrorAction SilentlyContinue) {',
+          '  Restart-Service "deadline10launcherservice"',
+          '} Else {',
+          '  & "$DEADLINE_PATH/deadlinelauncher.exe" -shutdownall 2>&1',
+          '  & "$DEADLINE_PATH/deadlinelauncher.exe" 2>&1',
```
Comment (ddneilson) [inline packages/aws-rfdk/lib/deadline/lib/rq-connection.ts]: I see below that you added the missing `-nogui` options. Add it here as well?

**Review by ddneilson — CHANGES_REQUESTED** [review]

**Review by horsmand — DISMISSED** [review]

File: packages/aws-rfdk/lib/deadline/lib/rq-connection.ts (hunk 1 above)
Comment (jusiskin) [reply packages/aws-rfdk/lib/deadline/lib/rq-connection.ts]: Good catch - fixed

**Review by ddneilson — DISMISSED** [review]

**Review by ddneilson — APPROVED** [review]

**Review by horsmand — APPROVED** [review]
